# Standards: 0.1
---
- name: Check existing install
  register: prometheus_vcd_sd_version_check
  failed_when: False
  changed_when: False
  check_mode: False
  command: /usr/bin/prometheus-vcd-sd --version
  tags:
    - prometheus-vcd-sd

- name: Fact version change
  set_fact:
    prometheus_vcd_sd_version_changed: "{{ prometheus_vcd_sd_version_check.rc != 0 or (prometheus_vcd_sd_version_check.stdout_lines is defined and prometheus_vcd_sd_version not in prometheus_vcd_sd_version_check.stdout_lines[0]) | bool }}"
  tags:
    - prometheus-vcd-sd

- name: Download defined binary
  when: prometheus_vcd_sd_version_changed
  notify:
    - Restart prometheus-vcd-sd
  get_url:
    url: "{{ prometheus_vcd_sd_download }}"
    dest: /usr/bin/prometheus-vcd-sd
    remote_src: True
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - prometheus-vcd-sd

- name: Create credentials directory
  file:
    path: "{{ prometheus_vcd_sd_credentials_file | dirname }}"
    owner: "{{ prometheus_vcd_sd_owner }}"
    group: "{{ prometheus_vcd_sd_group }}"
    state: directory
  tags:
    - prometheus-vcd-sd

- name: Write credentials config
  notify:
    - Restart prometheus-vcd-sd
  template:
    src: config.j2
    dest: "{{ prometheus_vcd_sd_credentials_file }}"
    owner: "{{ prometheus_vcd_sd_owner }}"
    group: "{{ prometheus_vcd_sd_group }}"
    mode: u=rw,g=rw,o=
  tags:
    - prometheus-vcd-sd

- name: Create output directory
  file:
    path: "{{ prometheus_vcd_sd_output_file | dirname }}"
    owner: "{{ prometheus_vcd_sd_owner }}"
    group: "{{ prometheus_vcd_sd_group }}"
    state: directory
  tags:
    - prometheus-vcd-sd

- name: Create output config
  copy:
    content: "{}"
    dest: "{{ prometheus_vcd_sd_output_file }}"
    force: False
    owner: "{{ prometheus_vcd_sd_owner }}"
    group: "{{ prometheus_vcd_sd_group }}"
    mode: u=rw,g=rw,o=
  tags:
    - prometheus-vcd-sd

- name: Write default config
  notify:
    - Restart prometheus-vcd-sd
  template:
    src: default.j2
    dest: /etc/default/prometheus-vcd-sd
  tags:
    - prometheus-vcd-sd

- name: Write service file
  notify:
    - Restart prometheus-vcd-sd
  template:
    src: service.j2
    dest: /etc/systemd/system/prometheus-vcd-sd.service
  tags:
    - prometheus-vcd-sd

- name: Start prometheus-vcd-sd service
  systemd:
    name: prometheus-vcd-sd
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - prometheus-vcd-sd

...
